### ISSUE TITLE
Error when importing Evergreen ILS records

### ISSUE THREAD

**Issue by ahazaril** [mdnoble73/aspen-discovery#1596]
Error when importing Evergreen ILS records:

[main] ERROR 01/07 19:29:33,276 - URL to post (/osrf-gateway-v1) is malformed
java.net.MalformedURLException: no protocol: /osrf-gateway-v1
        at java.net.URL.<init>(URL.java:611) ~[?:1.8.0_392]
        at java.net.URL.<init>(URL.java:508) ~[?:1.8.0_392]
        at java.net.URL.<init>(URL.java:457) ~[?:1.8.0_392]
        at com.turning_leaf_technologies.net.NetworkUtils.postToURL(NetworkUtils.java:153) [evergreen_export.jar:?]
        at com.turning_leaf_technologies.net.NetworkUtils.postToURL(NetworkUtils.java:111) [evergreen_export.jar:?]
        at org.aspendiscovery.evergreen_export.EvergreenExportMain.getAPIAuthToken(EvergreenExportMain.java:1761) [evergreen_export.jar:?]
        at org.aspendiscovery.evergreen_export.EvergreenExportMain.main(EvergreenExportMain.java:128) [evergreen_export.jar:?]
[main] ERROR 01/07 19:29:33,312 - URL to post (/opac/extras/unapi?id=tag::U2@bre/1{holdings_xml,acp}&format=marcxml) is malformed
java.net.MalformedURLException: no protocol: /opac/extras/unapi?id=tag::U2@bre/1{holdings_xml,acp}&format=marcxml
        at java.net.URL.<init>(URL.java:611) ~[?:1.8.0_392]
        at java.net.URL.<init>(URL.java:508) ~[?:1.8.0_392]
        at java.net.URL.<init>(URL.java:457) ~[?:1.8.0_392]
        at com.turning_leaf_technologies.net.NetworkUtils.getURL(NetworkUtils.java:39) [evergreen_export.jar:?]
        at com.turning_leaf_technologies.net.NetworkUtils.getURL(NetworkUtils.java:34) [evergreen_export.jar:?]
        at com.turning_leaf_technologies.net.NetworkUtils.getURL(NetworkUtils.java:31) [evergreen_export.jar:?]
        at org.aspendiscovery.evergreen_export.EvergreenExportMain.callEvergreenAPI(EvergreenExportMain.java:1672) [evergreen_export.jar:?]
        at org.aspendiscovery.evergreen_export.EvergreenExportMain.processGetBibsRequest(EvergreenExportMain.java:1426) [evergreen_export.jar:?]
        at org.aspendiscovery.evergreen_export.EvergreenExportMain.updateBibFromEvergreen(EvergreenExportMain.java:1409) [evergreen_export.jar:?]
        at org.aspendiscovery.evergreen_export.EvergreenExportMain.main(EvergreenExportMain.java:164) [evergreen_export.jar:?]
[main] ERROR 01/07 19:29:33,312 - URL to post (/opac/extras/unapi?id=tag::U2@bre/1{holdings_xml,acp}&format=marcxml) is malformed
java.net.MalformedURLException: no protocol: /opac/extras/unapi?id=tag::U2@bre/1{holdings_xml,acp}&format=marcxml
        at java.net.URL.<init>(URL.java:611) ~[?:1.8.0_392]
        at java.net.URL.<init>(URL.java:508) ~[?:1.8.0_392]
        at java.net.URL.<init>(URL.java:457) ~[?:1.8.0_392]
        at com.turning_leaf_technologies.net.NetworkUtils.getURL(NetworkUtils.java:39) [evergreen_export.jar:?]
        at com.turning_leaf_technologies.net.NetworkUtils.getURL(NetworkUtils.java:34) [evergreen_export.jar:?]
        at com.turning_leaf_technologies.net.NetworkUtils.getURL(NetworkUtils.java:31) [evergreen_export.jar:?]
        at org.aspendiscovery.evergreen_export.EvergreenExportMain.callEvergreenAPI(EvergreenExportMain.java:1672) [evergreen_export.jar:?]
        at org.aspendiscovery.evergreen_export.EvergreenExportMain.processGetBibsRequest(EvergreenExportMain.java:1426) [evergreen_export.jar:?]
        at org.aspendiscovery.evergreen_export.EvergreenExportMain.updateBibFromEvergreen(EvergreenExportMain.java:1409) [evergreen_export.jar:?]
        at org.aspendiscovery.evergreen_export.EvergreenExportMain.main(EvergreenExportMain.java:164) [evergreen_export.jar:?]
[main] ERROR 01/07 19:29:33,313 - URL to post (/opac/extras/unapi?id=tag::U2@bre/1{holdings_xml,acp}&format=marcxml) is malformed
java.net.MalformedURLException: no protocol: /opac/extras/unapi?id=tag::U2@bre/1{holdings_xml,acp}&format=marcxml
        at java.net.URL.<init>(URL.java:611) ~[?:1.8.0_392]
        at java.net.URL.<init>(URL.java:508) ~[?:1.8.0_392]
        at java.net.URL.<init>(URL.java:457) ~[?:1.8.0_392]
        at com.turning_leaf_technologies.net.NetworkUtils.getURL(NetworkUtils.java:39) [evergreen_export.jar:?]
        at com.turning_leaf_technologies.net.NetworkUtils.getURL(NetworkUtils.java:34) [evergreen_export.jar:?]
        at com.turning_leaf_technologies.net.NetworkUtils.getURL(NetworkUtils.java:31) [evergreen_export.jar:?]
        at org.aspendiscovery.evergreen_export.EvergreenExportMain.callEvergreenAPI(EvergreenExportMain.java:1672) [evergreen_export.jar:?]
        at org.aspendiscovery.evergreen_export.EvergreenExportMain.processGetBibsRequest(EvergreenExportMain.java:1426) [evergreen_export.jar:?]
        at org.aspendiscovery.evergreen_export.EvergreenExportMain.updateBibFromEvergreen(EvergreenExportMain.java:1409) [evergreen_export.jar:?]
        at org.aspendiscovery.evergreen_export.EvergreenExportMain.main(EvergreenExportMain.java:164) [evergreen_export.jar:?]
[main] ERROR 01/07 19:29:33,324 - Could not get bibs from /opac/extras/unapi?id=tag::U2@bre/1{holdings_xml,acp}&format=marcxml -1 URL to post (/opac/extras/unapi?id=tag::U2@bre/1{holdings_xml,acp}&format=marcxml) is malformed

**Comment by mdnoble73** [comment]
That looks like you don't have a URL to Evergreen in your account profile.

**Comment by mdnoble73** [comment]
Does the directory /data/aspen-discovery/kpssk.production/ils/marc/ exist? It sounds like the data directory is not created properly.  What OS are you installing on?

**Comment by ahazaril** [comment]
Yes, the path is valid. When I'm trying to import again, no data are imported including patrons data.

**Comment by ahazaril** [comment]
When I tried to import 1 records, and re-indexed, the OPAC shows:

Oops, an error occurred 
This error has been logged and we are working on a fix. 
Call to a member function treatVolumeHoldsAsItemHolds() on null 
Please contact the Library Reference Department for assistance

**Comment by mdnoble73** [comment]
It looks like the Indexing Profile and Account Profile don't match so Aspen can't load the driver properly.

**Comment by mdnoble73** [comment]
Closing for now, but please let me know if you need additional assistance.

**Comment by ahazaril** [comment]
Hi! Sorry i really forgot to response, can you show me how to configure for Evergeen ILS?

**Comment by mdnoble73** [comment]
We offer support services for Aspen Discovery at ByWater Solutions.  If you'd like assistance with configuration, we'd be happy to help out.  Please email me at mark@bywatersolutions.com so we can discuss your needs.
